/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.1.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_mainwindowClass
{
public:
    QAction *actionImport_Ply;
    QAction *actionSave_Ply;
    QAction *actionShow_Samples;
    QAction *actionShow_Original;
    QAction *actionShow_Neighborhood_Ball;
    QAction *actionCull_Points;
    QAction *actionSample_Color;
    QAction *actionOriginal_Color;
    QAction *actionBackground_Color;
    QAction *actionAmbient_Color;
    QAction *actionDiffuse_Color;
    QAction *actionSpecular_Color;
    QAction *actionLight_On_Off;
    QAction *actionInitial_Sampling;
    QAction *actionNormalize;
    QAction *actionDownSample;
    QAction *actionSubSample;
    QAction *actionSnapShot;
    QAction *actionShow_Normals;
    QAction *actionFeature_Color;
    QAction *actionNormal_Color;
    QAction *actionWLOP_2;
    QAction *actionRun_Wlop;
    QAction *actionWLOP_Setting;
    QAction *actionRun_PCA;
    QAction *actionNormal_Setting;
    QAction *actionReorientate;
    QAction *actionQuad;
    QAction *actionDot;
    QAction *actionCircle;
    QAction *actionQuad_2;
    QAction *actionDot_2;
    QAction *actionCircle_2;
    QAction *actionInitial_Sampling_2;
    QAction *actionAuto_Play;
    QAction *actionStop;
    QAction *actionStep;
    QAction *actionJump;
    QAction *actionSkeleton_Setting;
    QAction *actionUpsample_Setting;
    QAction *actionClear_Data;
    QAction *actionFff;
    QAction *actionShow_Normal_diff;
    QAction *actionShow_Vectors;
    QAction *actionShow_Tangent;
    QAction *actionLasso;
    QAction *actionSnap;
    QAction *actionCut;
    QAction *actionCopy;
    QAction *actionPaste;
    QAction *actionRender_sample_as_disk;
    QAction *actionRender_Sample_Points;
    QAction *actionShow_cutRadii;
    QAction *actionOutputProfilesAsImage;
    QAction *actionSolve_transfomr;
    QAction *actionShow_Samples_2;
    QAction *actionShow_Original_2;
    QAction *actionEditMode;
    QAction *actionSave_Skel;
    QAction *actionUndo;
    QAction *actionRedo;
    QAction *actionEditProfile;
    QAction *actionShowCv;
    QAction *actionSegment;
    QAction *actionInitSegment;
    QAction *actionRecenter;
    QAction *actionShow3dtemplates;
    QAction *actionGet3dTemplates;
    QAction *actionGet3dJoints;
    QAction *actionShow3dJoints;
    QAction *actionSnapTips;
    QAction *actionUpdateSurface;
    QAction *actionShow_trajectory;
    QAction *actionSave_og_nbs;
    QAction *actionLoad_og_nbs;
    QAction *actionSave_mesh;
    QAction *actionLoad_mesh;
    QAction *actionSave_brch_mesh;
    QAction *actionSave_settings;
    QAction *actionLoad_settings;
    QAction *actionVideoMode;
    QAction *actionCameraRotate;
    QAction *actionSnapShot_2;
    QAction *actionSweepingAnimation;
    QAction *actionShow_skeletonConfidence;
    QAction *actionShow_points;
    QAction *actionShow_cullFace;
    QAction *actionShow_meshVertOnly;
    QAction *actionShow_settings;
    QAction *actionShow_trajectory_2;
    QAction *actionShow_seedProfile;
    QAction *actionShow_skeleton;
    QAction *actionShow_mesh;
    QAction *actionShow_resultProfile;
    QAction *actionConfig;
    QAction *actionShow_trajectory_3;
    QAction *actionShow_seedProfile_2;
    QAction *actionShow_skeleton_2;
    QAction *actionShow_mesh_2;
    QAction *actionShow_resultProfile_2;
    QAction *actionShow_skeletonConfidence_2;
    QAction *actionShow_profileConfidence_2;
    QAction *actionShow_cullFace_2;
    QAction *actionShow_meshVertOnly_2;
    QAction *actionShow_settings_2;
    QAction *actionShow_cutRadii_2;
    QWidget *centralWidget;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QMenu *menuRender;
    QMenu *menuOperations;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *mainwindowClass)
    {
        if (mainwindowClass->objectName().isEmpty())
            mainwindowClass->setObjectName(QStringLiteral("mainwindowClass"));
        mainwindowClass->resize(1008, 824);
        mainwindowClass->setMinimumSize(QSize(55, 55));
        mainwindowClass->setSizeIncrement(QSize(5, 5));
        mainwindowClass->setBaseSize(QSize(1, 1));
        mainwindowClass->setAcceptDrops(true);
        QIcon icon;
        icon.addFile(QStringLiteral("Icons/morfit.png"), QSize(), QIcon::Normal, QIcon::Off);
        mainwindowClass->setWindowIcon(icon);
        mainwindowClass->setIconSize(QSize(36, 36));
        mainwindowClass->setDocumentMode(false);
        mainwindowClass->setTabShape(QTabWidget::Rounded);
        actionImport_Ply = new QAction(mainwindowClass);
        actionImport_Ply->setObjectName(QStringLiteral("actionImport_Ply"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/mainwindow/Icons/open.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionImport_Ply->setIcon(icon1);
        actionImport_Ply->setShortcutContext(Qt::WidgetShortcut);
        actionImport_Ply->setMenuRole(QAction::TextHeuristicRole);
        actionSave_Ply = new QAction(mainwindowClass);
        actionSave_Ply->setObjectName(QStringLiteral("actionSave_Ply"));
        QIcon icon2;
        icon2.addFile(QStringLiteral(":/mainwindow/Icons/save.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_Ply->setIcon(icon2);
        actionShow_Samples = new QAction(mainwindowClass);
        actionShow_Samples->setObjectName(QStringLiteral("actionShow_Samples"));
        actionShow_Samples->setCheckable(true);
        actionShow_Original = new QAction(mainwindowClass);
        actionShow_Original->setObjectName(QStringLiteral("actionShow_Original"));
        actionShow_Original->setCheckable(true);
        actionShow_Neighborhood_Ball = new QAction(mainwindowClass);
        actionShow_Neighborhood_Ball->setObjectName(QStringLiteral("actionShow_Neighborhood_Ball"));
        actionShow_Neighborhood_Ball->setCheckable(true);
        actionCull_Points = new QAction(mainwindowClass);
        actionCull_Points->setObjectName(QStringLiteral("actionCull_Points"));
        actionCull_Points->setCheckable(true);
        actionSample_Color = new QAction(mainwindowClass);
        actionSample_Color->setObjectName(QStringLiteral("actionSample_Color"));
        actionOriginal_Color = new QAction(mainwindowClass);
        actionOriginal_Color->setObjectName(QStringLiteral("actionOriginal_Color"));
        actionBackground_Color = new QAction(mainwindowClass);
        actionBackground_Color->setObjectName(QStringLiteral("actionBackground_Color"));
        actionAmbient_Color = new QAction(mainwindowClass);
        actionAmbient_Color->setObjectName(QStringLiteral("actionAmbient_Color"));
        actionDiffuse_Color = new QAction(mainwindowClass);
        actionDiffuse_Color->setObjectName(QStringLiteral("actionDiffuse_Color"));
        actionSpecular_Color = new QAction(mainwindowClass);
        actionSpecular_Color->setObjectName(QStringLiteral("actionSpecular_Color"));
        actionLight_On_Off = new QAction(mainwindowClass);
        actionLight_On_Off->setObjectName(QStringLiteral("actionLight_On_Off"));
        actionLight_On_Off->setCheckable(true);
        QIcon icon3;
        icon3.addFile(QStringLiteral(":/mainwindow/Icons/lighton.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLight_On_Off->setIcon(icon3);
        actionInitial_Sampling = new QAction(mainwindowClass);
        actionInitial_Sampling->setObjectName(QStringLiteral("actionInitial_Sampling"));
        actionNormalize = new QAction(mainwindowClass);
        actionNormalize->setObjectName(QStringLiteral("actionNormalize"));
        actionDownSample = new QAction(mainwindowClass);
        actionDownSample->setObjectName(QStringLiteral("actionDownSample"));
        actionSubSample = new QAction(mainwindowClass);
        actionSubSample->setObjectName(QStringLiteral("actionSubSample"));
        actionSnapShot = new QAction(mainwindowClass);
        actionSnapShot->setObjectName(QStringLiteral("actionSnapShot"));
        QIcon icon4;
        icon4.addFile(QStringLiteral(":/mainwindow/Icons/125.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSnapShot->setIcon(icon4);
        actionShow_Normals = new QAction(mainwindowClass);
        actionShow_Normals->setObjectName(QStringLiteral("actionShow_Normals"));
        actionShow_Normals->setCheckable(true);
        actionFeature_Color = new QAction(mainwindowClass);
        actionFeature_Color->setObjectName(QStringLiteral("actionFeature_Color"));
        actionNormal_Color = new QAction(mainwindowClass);
        actionNormal_Color->setObjectName(QStringLiteral("actionNormal_Color"));
        actionWLOP_2 = new QAction(mainwindowClass);
        actionWLOP_2->setObjectName(QStringLiteral("actionWLOP_2"));
        actionRun_Wlop = new QAction(mainwindowClass);
        actionRun_Wlop->setObjectName(QStringLiteral("actionRun_Wlop"));
        actionWLOP_Setting = new QAction(mainwindowClass);
        actionWLOP_Setting->setObjectName(QStringLiteral("actionWLOP_Setting"));
        actionRun_PCA = new QAction(mainwindowClass);
        actionRun_PCA->setObjectName(QStringLiteral("actionRun_PCA"));
        actionNormal_Setting = new QAction(mainwindowClass);
        actionNormal_Setting->setObjectName(QStringLiteral("actionNormal_Setting"));
        actionReorientate = new QAction(mainwindowClass);
        actionReorientate->setObjectName(QStringLiteral("actionReorientate"));
        actionQuad = new QAction(mainwindowClass);
        actionQuad->setObjectName(QStringLiteral("actionQuad"));
        actionDot = new QAction(mainwindowClass);
        actionDot->setObjectName(QStringLiteral("actionDot"));
        actionCircle = new QAction(mainwindowClass);
        actionCircle->setObjectName(QStringLiteral("actionCircle"));
        actionQuad_2 = new QAction(mainwindowClass);
        actionQuad_2->setObjectName(QStringLiteral("actionQuad_2"));
        actionDot_2 = new QAction(mainwindowClass);
        actionDot_2->setObjectName(QStringLiteral("actionDot_2"));
        actionCircle_2 = new QAction(mainwindowClass);
        actionCircle_2->setObjectName(QStringLiteral("actionCircle_2"));
        actionInitial_Sampling_2 = new QAction(mainwindowClass);
        actionInitial_Sampling_2->setObjectName(QStringLiteral("actionInitial_Sampling_2"));
        actionAuto_Play = new QAction(mainwindowClass);
        actionAuto_Play->setObjectName(QStringLiteral("actionAuto_Play"));
        actionStop = new QAction(mainwindowClass);
        actionStop->setObjectName(QStringLiteral("actionStop"));
        actionStep = new QAction(mainwindowClass);
        actionStep->setObjectName(QStringLiteral("actionStep"));
        actionJump = new QAction(mainwindowClass);
        actionJump->setObjectName(QStringLiteral("actionJump"));
        actionSkeleton_Setting = new QAction(mainwindowClass);
        actionSkeleton_Setting->setObjectName(QStringLiteral("actionSkeleton_Setting"));
        actionUpsample_Setting = new QAction(mainwindowClass);
        actionUpsample_Setting->setObjectName(QStringLiteral("actionUpsample_Setting"));
        actionClear_Data = new QAction(mainwindowClass);
        actionClear_Data->setObjectName(QStringLiteral("actionClear_Data"));
        actionFff = new QAction(mainwindowClass);
        actionFff->setObjectName(QStringLiteral("actionFff"));
        actionShow_Normal_diff = new QAction(mainwindowClass);
        actionShow_Normal_diff->setObjectName(QStringLiteral("actionShow_Normal_diff"));
        actionShow_Normal_diff->setCheckable(true);
        actionShow_Vectors = new QAction(mainwindowClass);
        actionShow_Vectors->setObjectName(QStringLiteral("actionShow_Vectors"));
        actionShow_Vectors->setCheckable(true);
        actionShow_Tangent = new QAction(mainwindowClass);
        actionShow_Tangent->setObjectName(QStringLiteral("actionShow_Tangent"));
        actionShow_Tangent->setCheckable(true);
        actionLasso = new QAction(mainwindowClass);
        actionLasso->setObjectName(QStringLiteral("actionLasso"));
        actionLasso->setCheckable(true);
        actionLasso->setChecked(false);
        actionLasso->setEnabled(false);
        QIcon icon5;
        icon5.addFile(QStringLiteral("Icons/lasso.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionLasso->setIcon(icon5);
        actionSnap = new QAction(mainwindowClass);
        actionSnap->setObjectName(QStringLiteral("actionSnap"));
        actionSnap->setCheckable(false);
        actionSnap->setEnabled(false);
        QIcon icon6;
        icon6.addFile(QStringLiteral("Icons/SnapIcon1.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSnap->setIcon(icon6);
        actionCut = new QAction(mainwindowClass);
        actionCut->setObjectName(QStringLiteral("actionCut"));
        QIcon icon7;
        icon7.addFile(QStringLiteral("Icons/cut.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCut->setIcon(icon7);
        actionCut->setShortcutContext(Qt::WindowShortcut);
        actionCopy = new QAction(mainwindowClass);
        actionCopy->setObjectName(QStringLiteral("actionCopy"));
        QIcon icon8;
        icon8.addFile(QStringLiteral("Icons/copy.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionCopy->setIcon(icon8);
        actionPaste = new QAction(mainwindowClass);
        actionPaste->setObjectName(QStringLiteral("actionPaste"));
        QIcon icon9;
        icon9.addFile(QStringLiteral("Icons/paste.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionPaste->setIcon(icon9);
        actionRender_sample_as_disk = new QAction(mainwindowClass);
        actionRender_sample_as_disk->setObjectName(QStringLiteral("actionRender_sample_as_disk"));
        actionRender_sample_as_disk->setCheckable(true);
        actionRender_Sample_Points = new QAction(mainwindowClass);
        actionRender_Sample_Points->setObjectName(QStringLiteral("actionRender_Sample_Points"));
        actionShow_cutRadii = new QAction(mainwindowClass);
        actionShow_cutRadii->setObjectName(QStringLiteral("actionShow_cutRadii"));
        actionShow_cutRadii->setCheckable(true);
        actionOutputProfilesAsImage = new QAction(mainwindowClass);
        actionOutputProfilesAsImage->setObjectName(QStringLiteral("actionOutputProfilesAsImage"));
        actionOutputProfilesAsImage->setCheckable(false);
        actionSolve_transfomr = new QAction(mainwindowClass);
        actionSolve_transfomr->setObjectName(QStringLiteral("actionSolve_transfomr"));
        actionSolve_transfomr->setCheckable(false);
        actionShow_Samples_2 = new QAction(mainwindowClass);
        actionShow_Samples_2->setObjectName(QStringLiteral("actionShow_Samples_2"));
        actionShow_Samples_2->setCheckable(true);
        actionShow_Samples_2->setChecked(true);
        actionShow_Original_2 = new QAction(mainwindowClass);
        actionShow_Original_2->setObjectName(QStringLiteral("actionShow_Original_2"));
        actionShow_Original_2->setCheckable(true);
        actionShow_Original_2->setChecked(true);
        actionEditMode = new QAction(mainwindowClass);
        actionEditMode->setObjectName(QStringLiteral("actionEditMode"));
        actionEditMode->setCheckable(true);
        actionEditMode->setShortcutContext(Qt::ApplicationShortcut);
        actionSave_Skel = new QAction(mainwindowClass);
        actionSave_Skel->setObjectName(QStringLiteral("actionSave_Skel"));
        QIcon icon10;
        icon10.addFile(QStringLiteral("Icons/skel.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionSave_Skel->setIcon(icon10);
        actionUndo = new QAction(mainwindowClass);
        actionUndo->setObjectName(QStringLiteral("actionUndo"));
        actionUndo->setShortcutContext(Qt::ApplicationShortcut);
        actionRedo = new QAction(mainwindowClass);
        actionRedo->setObjectName(QStringLiteral("actionRedo"));
        actionRedo->setShortcutContext(Qt::ApplicationShortcut);
        actionEditProfile = new QAction(mainwindowClass);
        actionEditProfile->setObjectName(QStringLiteral("actionEditProfile"));
        actionEditProfile->setCheckable(true);
        actionEditProfile->setShortcutContext(Qt::ApplicationShortcut);
        actionShowCv = new QAction(mainwindowClass);
        actionShowCv->setObjectName(QStringLiteral("actionShowCv"));
        actionShowCv->setCheckable(true);
        actionShowCv->setShortcutContext(Qt::ApplicationShortcut);
        actionSegment = new QAction(mainwindowClass);
        actionSegment->setObjectName(QStringLiteral("actionSegment"));
        actionSegment->setCheckable(true);
        actionInitSegment = new QAction(mainwindowClass);
        actionInitSegment->setObjectName(QStringLiteral("actionInitSegment"));
        actionRecenter = new QAction(mainwindowClass);
        actionRecenter->setObjectName(QStringLiteral("actionRecenter"));
        actionShow3dtemplates = new QAction(mainwindowClass);
        actionShow3dtemplates->setObjectName(QStringLiteral("actionShow3dtemplates"));
        actionShow3dtemplates->setCheckable(true);
        actionGet3dTemplates = new QAction(mainwindowClass);
        actionGet3dTemplates->setObjectName(QStringLiteral("actionGet3dTemplates"));
        actionGet3dJoints = new QAction(mainwindowClass);
        actionGet3dJoints->setObjectName(QStringLiteral("actionGet3dJoints"));
        actionShow3dJoints = new QAction(mainwindowClass);
        actionShow3dJoints->setObjectName(QStringLiteral("actionShow3dJoints"));
        actionShow3dJoints->setCheckable(true);
        actionShow3dJoints->setChecked(true);
        actionSnapTips = new QAction(mainwindowClass);
        actionSnapTips->setObjectName(QStringLiteral("actionSnapTips"));
        actionUpdateSurface = new QAction(mainwindowClass);
        actionUpdateSurface->setObjectName(QStringLiteral("actionUpdateSurface"));
        actionShow_trajectory = new QAction(mainwindowClass);
        actionShow_trajectory->setObjectName(QStringLiteral("actionShow_trajectory"));
        actionShow_trajectory->setCheckable(true);
        actionSave_og_nbs = new QAction(mainwindowClass);
        actionSave_og_nbs->setObjectName(QStringLiteral("actionSave_og_nbs"));
        actionLoad_og_nbs = new QAction(mainwindowClass);
        actionLoad_og_nbs->setObjectName(QStringLiteral("actionLoad_og_nbs"));
        actionSave_mesh = new QAction(mainwindowClass);
        actionSave_mesh->setObjectName(QStringLiteral("actionSave_mesh"));
        actionLoad_mesh = new QAction(mainwindowClass);
        actionLoad_mesh->setObjectName(QStringLiteral("actionLoad_mesh"));
        actionSave_brch_mesh = new QAction(mainwindowClass);
        actionSave_brch_mesh->setObjectName(QStringLiteral("actionSave_brch_mesh"));
        actionSave_settings = new QAction(mainwindowClass);
        actionSave_settings->setObjectName(QStringLiteral("actionSave_settings"));
        actionLoad_settings = new QAction(mainwindowClass);
        actionLoad_settings->setObjectName(QStringLiteral("actionLoad_settings"));
        actionVideoMode = new QAction(mainwindowClass);
        actionVideoMode->setObjectName(QStringLiteral("actionVideoMode"));
        actionVideoMode->setCheckable(true);
        actionCameraRotate = new QAction(mainwindowClass);
        actionCameraRotate->setObjectName(QStringLiteral("actionCameraRotate"));
        actionCameraRotate->setCheckable(true);
        actionSnapShot_2 = new QAction(mainwindowClass);
        actionSnapShot_2->setObjectName(QStringLiteral("actionSnapShot_2"));
        actionSnapShot_2->setIcon(icon4);
        actionSweepingAnimation = new QAction(mainwindowClass);
        actionSweepingAnimation->setObjectName(QStringLiteral("actionSweepingAnimation"));
        actionSweepingAnimation->setCheckable(true);
        actionShow_skeletonConfidence = new QAction(mainwindowClass);
        actionShow_skeletonConfidence->setObjectName(QStringLiteral("actionShow_skeletonConfidence"));
        actionShow_skeletonConfidence->setCheckable(true);
        actionShow_skeletonConfidence->setChecked(false);
        actionShow_points = new QAction(mainwindowClass);
        actionShow_points->setObjectName(QStringLiteral("actionShow_points"));
        actionShow_points->setCheckable(true);
        actionShow_points->setChecked(true);
        actionShow_cullFace = new QAction(mainwindowClass);
        actionShow_cullFace->setObjectName(QStringLiteral("actionShow_cullFace"));
        actionShow_cullFace->setCheckable(true);
        actionShow_cullFace->setChecked(false);
        actionShow_meshVertOnly = new QAction(mainwindowClass);
        actionShow_meshVertOnly->setObjectName(QStringLiteral("actionShow_meshVertOnly"));
        actionShow_meshVertOnly->setCheckable(true);
        actionShow_meshVertOnly->setChecked(false);
        actionShow_settings = new QAction(mainwindowClass);
        actionShow_settings->setObjectName(QStringLiteral("actionShow_settings"));
        actionShow_settings->setCheckable(true);
        actionShow_settings->setChecked(false);
        actionShow_trajectory_2 = new QAction(mainwindowClass);
        actionShow_trajectory_2->setObjectName(QStringLiteral("actionShow_trajectory_2"));
        actionShow_trajectory_2->setCheckable(true);
        actionShow_trajectory_2->setChecked(false);
        actionShow_seedProfile = new QAction(mainwindowClass);
        actionShow_seedProfile->setObjectName(QStringLiteral("actionShow_seedProfile"));
        actionShow_seedProfile->setCheckable(true);
        actionShow_seedProfile->setChecked(true);
        actionShow_skeleton = new QAction(mainwindowClass);
        actionShow_skeleton->setObjectName(QStringLiteral("actionShow_skeleton"));
        actionShow_skeleton->setCheckable(true);
        actionShow_skeleton->setChecked(true);
        actionShow_mesh = new QAction(mainwindowClass);
        actionShow_mesh->setObjectName(QStringLiteral("actionShow_mesh"));
        actionShow_mesh->setCheckable(true);
        actionShow_mesh->setChecked(true);
        actionShow_resultProfile = new QAction(mainwindowClass);
        actionShow_resultProfile->setObjectName(QStringLiteral("actionShow_resultProfile"));
        actionShow_resultProfile->setCheckable(true);
        actionShow_resultProfile->setChecked(false);
        actionConfig = new QAction(mainwindowClass);
        actionConfig->setObjectName(QStringLiteral("actionConfig"));
        actionConfig->setCheckable(true);
        QIcon icon11;
        icon11.addFile(QStringLiteral("Icons/Parameters-512.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionConfig->setIcon(icon11);
        actionShow_trajectory_3 = new QAction(mainwindowClass);
        actionShow_trajectory_3->setObjectName(QStringLiteral("actionShow_trajectory_3"));
        actionShow_trajectory_3->setCheckable(true);
        QIcon icon12;
        icon12.addFile(QStringLiteral(":/mainwindow/Icons/gowalla_128x128-32.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_trajectory_3->setIcon(icon12);
        actionShow_seedProfile_2 = new QAction(mainwindowClass);
        actionShow_seedProfile_2->setObjectName(QStringLiteral("actionShow_seedProfile_2"));
        actionShow_seedProfile_2->setCheckable(true);
        QIcon icon13;
        icon13.addFile(QStringLiteral(":/mainwindow/Icons/select_face.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_seedProfile_2->setIcon(icon13);
        actionShow_skeleton_2 = new QAction(mainwindowClass);
        actionShow_skeleton_2->setObjectName(QStringLiteral("actionShow_skeleton_2"));
        actionShow_skeleton_2->setCheckable(true);
        QIcon icon14;
        icon14.addFile(QStringLiteral(":/mainwindow/Icons/heyzap_128x128-32.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_skeleton_2->setIcon(icon14);
        actionShow_mesh_2 = new QAction(mainwindowClass);
        actionShow_mesh_2->setObjectName(QStringLiteral("actionShow_mesh_2"));
        actionShow_mesh_2->setCheckable(true);
        actionShow_mesh_2->setChecked(false);
        QIcon icon15;
        icon15.addFile(QStringLiteral(":/mainwindow/Icons/edgecollapse.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_mesh_2->setIcon(icon15);
        actionShow_resultProfile_2 = new QAction(mainwindowClass);
        actionShow_resultProfile_2->setObjectName(QStringLiteral("actionShow_resultProfile_2"));
        actionShow_resultProfile_2->setCheckable(true);
        QIcon icon16;
        icon16.addFile(QStringLiteral(":/mainwindow/Icons/color_red_ggr.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_resultProfile_2->setIcon(icon16);
        actionShow_skeletonConfidence_2 = new QAction(mainwindowClass);
        actionShow_skeletonConfidence_2->setObjectName(QStringLiteral("actionShow_skeletonConfidence_2"));
        actionShow_skeletonConfidence_2->setCheckable(true);
        QIcon icon17;
        icon17.addFile(QStringLiteral(":/mainwindow/Icons/selected.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_skeletonConfidence_2->setIcon(icon17);
        actionShow_profileConfidence_2 = new QAction(mainwindowClass);
        actionShow_profileConfidence_2->setObjectName(QStringLiteral("actionShow_profileConfidence_2"));
        actionShow_profileConfidence_2->setCheckable(true);
        QIcon icon18;
        icon18.addFile(QStringLiteral(":/mainwindow/Icons/smooth.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_profileConfidence_2->setIcon(icon18);
        actionShow_cullFace_2 = new QAction(mainwindowClass);
        actionShow_cullFace_2->setObjectName(QStringLiteral("actionShow_cullFace_2"));
        actionShow_cullFace_2->setCheckable(true);
        QIcon icon19;
        icon19.addFile(QStringLiteral(":/mainwindow/Icons/triangle.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_cullFace_2->setIcon(icon19);
        actionShow_meshVertOnly_2 = new QAction(mainwindowClass);
        actionShow_meshVertOnly_2->setObjectName(QStringLiteral("actionShow_meshVertOnly_2"));
        actionShow_meshVertOnly_2->setCheckable(true);
        QIcon icon20;
        icon20.addFile(QStringLiteral(":/mainwindow/Icons/edgesplit.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_meshVertOnly_2->setIcon(icon20);
        actionShow_settings_2 = new QAction(mainwindowClass);
        actionShow_settings_2->setObjectName(QStringLiteral("actionShow_settings_2"));
        actionShow_settings_2->setCheckable(true);
        QIcon icon21;
        icon21.addFile(QStringLiteral(":/mainwindow/Icons/settings_128x128-32.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_settings_2->setIcon(icon21);
        actionShow_cutRadii_2 = new QAction(mainwindowClass);
        actionShow_cutRadii_2->setObjectName(QStringLiteral("actionShow_cutRadii_2"));
        QIcon icon22;
        icon22.addFile(QStringLiteral(":/mainwindow/Icons/vertex.png"), QSize(), QIcon::Normal, QIcon::Off);
        actionShow_cutRadii_2->setIcon(icon22);
        centralWidget = new QWidget(mainwindowClass);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        mainwindowClass->setCentralWidget(centralWidget);
        menuBar = new QMenuBar(mainwindowClass);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 1008, 27));
        QFont font;
        font.setPointSize(12);
        menuBar->setFont(font);
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        menuRender = new QMenu(menuBar);
        menuRender->setObjectName(QStringLiteral("menuRender"));
        menuOperations = new QMenu(menuBar);
        menuOperations->setObjectName(QStringLiteral("menuOperations"));
        mainwindowClass->setMenuBar(menuBar);
        mainToolBar = new QToolBar(mainwindowClass);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        mainToolBar->setBaseSize(QSize(11, 11));
        mainToolBar->setToolButtonStyle(Qt::ToolButtonIconOnly);
        mainwindowClass->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(mainwindowClass);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        QFont font1;
        font1.setPointSize(16);
        statusBar->setFont(font1);
        mainwindowClass->setStatusBar(statusBar);

        menuBar->addAction(menuFile->menuAction());
        menuBar->addAction(menuRender->menuAction());
        menuBar->addAction(menuOperations->menuAction());
        menuFile->addAction(actionImport_Ply);
        menuFile->addAction(actionSave_Skel);
        menuRender->addAction(actionShow_cutRadii);
        menuRender->addAction(actionShow_points);
        menuRender->addAction(actionShow_skeleton);
        menuRender->addAction(actionShow_trajectory_2);
        menuRender->addAction(actionShow_seedProfile);
        menuRender->addAction(actionShow_mesh);
        menuRender->addAction(actionShow_resultProfile);
        menuRender->addAction(actionShow_skeletonConfidence);
        menuRender->addAction(actionShow_cullFace);
        menuRender->addAction(actionShow_meshVertOnly);
        menuRender->addAction(actionShow_settings);
        menuOperations->addAction(actionEditMode);
        menuOperations->addAction(actionUndo);
        menuOperations->addAction(actionRedo);
        mainToolBar->addAction(actionImport_Ply);
        mainToolBar->addAction(actionSnapShot_2);
        mainToolBar->addAction(actionSave_Skel);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSave_og_nbs);
        mainToolBar->addAction(actionLoad_og_nbs);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSave_mesh);
        mainToolBar->addAction(actionLoad_mesh);
        mainToolBar->addAction(actionSave_brch_mesh);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionSave_settings);
        mainToolBar->addAction(actionLoad_settings);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionRecenter);
        mainToolBar->addSeparator();
        mainToolBar->addAction(actionConfig);

        retranslateUi(mainwindowClass);

        QMetaObject::connectSlotsByName(mainwindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *mainwindowClass)
    {
        mainwindowClass->setWindowTitle(QApplication::translate("mainwindowClass", "Morfit", 0));
        actionImport_Ply->setText(QApplication::translate("mainwindowClass", "Import Ply+Skel", 0));
        actionImport_Ply->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+O", 0));
        actionSave_Ply->setText(QApplication::translate("mainwindowClass", "Save Ply", 0));
        actionSave_Ply->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+S", 0));
        actionShow_Samples->setText(QApplication::translate("mainwindowClass", "Show Samples", 0));
        actionShow_Original->setText(QApplication::translate("mainwindowClass", "Show Original Points", 0));
        actionShow_Neighborhood_Ball->setText(QApplication::translate("mainwindowClass", "Show Radius", 0));
        actionShow_Neighborhood_Ball->setShortcut(QApplication::translate("mainwindowClass", "Alt+R", 0));
        actionCull_Points->setText(QApplication::translate("mainwindowClass", "Cull Points", 0));
        actionCull_Points->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+T", 0));
        actionSample_Color->setText(QApplication::translate("mainwindowClass", "Sample Color", 0));
        actionOriginal_Color->setText(QApplication::translate("mainwindowClass", "Original Color", 0));
        actionBackground_Color->setText(QApplication::translate("mainwindowClass", "Background Color", 0));
        actionAmbient_Color->setText(QApplication::translate("mainwindowClass", "Ambient Color", 0));
        actionDiffuse_Color->setText(QApplication::translate("mainwindowClass", "Diffuse Color", 0));
        actionSpecular_Color->setText(QApplication::translate("mainwindowClass", "Specular Color", 0));
        actionLight_On_Off->setText(QApplication::translate("mainwindowClass", "Light On/Off", 0));
        actionInitial_Sampling->setText(QApplication::translate("mainwindowClass", "Initial Sampling", 0));
        actionNormalize->setText(QApplication::translate("mainwindowClass", "Normalize", 0));
        actionDownSample->setText(QApplication::translate("mainwindowClass", "DownSample", 0));
        actionSubSample->setText(QApplication::translate("mainwindowClass", "SubSample", 0));
        actionSnapShot->setText(QApplication::translate("mainwindowClass", "ScreenShot", 0));
        actionSnapShot->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+P", 0));
        actionShow_Normals->setText(QApplication::translate("mainwindowClass", "Show Normals", 0));
        actionShow_Normals->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+N, Ctrl+C", 0));
        actionFeature_Color->setText(QApplication::translate("mainwindowClass", "Feature Color", 0));
        actionNormal_Color->setText(QApplication::translate("mainwindowClass", "Normal Color", 0));
        actionWLOP_2->setText(QApplication::translate("mainwindowClass", "Skeletonization", 0));
        actionRun_Wlop->setText(QApplication::translate("mainwindowClass", "Run WLOP", 0));
        actionWLOP_Setting->setText(QApplication::translate("mainwindowClass", "WLOP Setting", 0));
        actionRun_PCA->setText(QApplication::translate("mainwindowClass", "Run PCA", 0));
        actionNormal_Setting->setText(QApplication::translate("mainwindowClass", "Normal Setting", 0));
        actionReorientate->setText(QApplication::translate("mainwindowClass", "Reorientate", 0));
        actionQuad->setText(QApplication::translate("mainwindowClass", "Quad", 0));
        actionDot->setText(QApplication::translate("mainwindowClass", "Dot", 0));
        actionCircle->setText(QApplication::translate("mainwindowClass", "Circle", 0));
        actionQuad_2->setText(QApplication::translate("mainwindowClass", "Quad", 0));
        actionDot_2->setText(QApplication::translate("mainwindowClass", "Dot", 0));
        actionCircle_2->setText(QApplication::translate("mainwindowClass", "Circle", 0));
        actionInitial_Sampling_2->setText(QApplication::translate("mainwindowClass", "Initialization", 0));
        actionAuto_Play->setText(QApplication::translate("mainwindowClass", "Auto Play", 0));
        actionStop->setText(QApplication::translate("mainwindowClass", "Stop", 0));
        actionStep->setText(QApplication::translate("mainwindowClass", "Step", 0));
        actionJump->setText(QApplication::translate("mainwindowClass", "Jump", 0));
        actionSkeleton_Setting->setText(QApplication::translate("mainwindowClass", "Skeleton Setting", 0));
        actionUpsample_Setting->setText(QApplication::translate("mainwindowClass", "Upsample Setting", 0));
        actionClear_Data->setText(QApplication::translate("mainwindowClass", "Clear data", 0));
        actionFff->setText(QApplication::translate("mainwindowClass", "fff", 0));
        actionShow_Normal_diff->setText(QApplication::translate("mainwindowClass", "Show Normal diff", 0));
        actionShow_Vectors->setText(QApplication::translate("mainwindowClass", "Show Vectors", 0));
        actionShow_Tangent->setText(QApplication::translate("mainwindowClass", "Show Tangent", 0));
        actionLasso->setText(QApplication::translate("mainwindowClass", "lasso", 0));
        actionLasso->setShortcut(QApplication::translate("mainwindowClass", "L", 0));
        actionSnap->setText(QApplication::translate("mainwindowClass", "snap", 0));
        actionSnap->setShortcut(QApplication::translate("mainwindowClass", "S", 0));
        actionCut->setText(QApplication::translate("mainwindowClass", "Cut", 0));
        actionCut->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+X", 0));
        actionCopy->setText(QApplication::translate("mainwindowClass", "Copy", 0));
        actionCopy->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+C", 0));
        actionPaste->setText(QApplication::translate("mainwindowClass", "Paste", 0));
        actionPaste->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+V", 0));
        actionRender_sample_as_disk->setText(QApplication::translate("mainwindowClass", "Render Sample Disks", 0));
        actionRender_Sample_Points->setText(QApplication::translate("mainwindowClass", "Render Sample Points", 0));
        actionShow_cutRadii->setText(QApplication::translate("mainwindowClass", "show cutRadii", 0));
        actionOutputProfilesAsImage->setText(QApplication::translate("mainwindowClass", "outputProfilesAsImage", 0));
        actionSolve_transfomr->setText(QApplication::translate("mainwindowClass", "solve transform", 0));
        actionShow_Samples_2->setText(QApplication::translate("mainwindowClass", "show reconstruction", 0));
        actionShow_Original_2->setText(QApplication::translate("mainwindowClass", "show original", 0));
        actionEditMode->setText(QApplication::translate("mainwindowClass", "EditSkel", 0));
        actionEditMode->setShortcut(QApplication::translate("mainwindowClass", "E", 0));
        actionSave_Skel->setText(QApplication::translate("mainwindowClass", "Save_Skel", 0));
        actionUndo->setText(QApplication::translate("mainwindowClass", "Undo", 0));
        actionUndo->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+Z", 0));
        actionRedo->setText(QApplication::translate("mainwindowClass", "Redo", 0));
        actionRedo->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+Y", 0));
        actionEditProfile->setText(QApplication::translate("mainwindowClass", "EditProfile", 0));
        actionShowCv->setText(QApplication::translate("mainwindowClass", "showCv", 0));
        actionSegment->setText(QApplication::translate("mainwindowClass", "segment", 0));
        actionSegment->setIconText(QApplication::translate("mainwindowClass", "segmentBranch", 0));
        actionInitSegment->setText(QApplication::translate("mainwindowClass", "initSegment", 0));
        actionRecenter->setText(QApplication::translate("mainwindowClass", "recenter skel", 0));
        actionShow3dtemplates->setText(QApplication::translate("mainwindowClass", "show3dtemplates", 0));
        actionGet3dTemplates->setText(QApplication::translate("mainwindowClass", "get3dTemplates", 0));
        actionGet3dJoints->setText(QApplication::translate("mainwindowClass", "get3dJoints", 0));
        actionShow3dJoints->setText(QApplication::translate("mainwindowClass", "show3dJoints", 0));
        actionSnapTips->setText(QApplication::translate("mainwindowClass", "snapTips", 0));
        actionUpdateSurface->setText(QApplication::translate("mainwindowClass", "update surface", 0));
        actionShow_trajectory->setText(QApplication::translate("mainwindowClass", "show trajectory", 0));
        actionSave_og_nbs->setText(QApplication::translate("mainwindowClass", "save og nbs", 0));
        actionLoad_og_nbs->setText(QApplication::translate("mainwindowClass", "load og nbs", 0));
        actionLoad_og_nbs->setShortcut(QApplication::translate("mainwindowClass", "[", 0));
        actionSave_mesh->setText(QApplication::translate("mainwindowClass", "save mesh", 0));
        actionLoad_mesh->setText(QApplication::translate("mainwindowClass", "load mesh", 0));
        actionSave_brch_mesh->setText(QApplication::translate("mainwindowClass", "save brch mesh", 0));
        actionSave_settings->setText(QApplication::translate("mainwindowClass", "save settings", 0));
        actionLoad_settings->setText(QApplication::translate("mainwindowClass", "load settings", 0));
        actionLoad_settings->setShortcut(QApplication::translate("mainwindowClass", "]", 0));
        actionVideoMode->setText(QApplication::translate("mainwindowClass", "videoMode", 0));
        actionCameraRotate->setText(QApplication::translate("mainwindowClass", "cameraRotate", 0));
        actionCameraRotate->setShortcut(QApplication::translate("mainwindowClass", "Ctrl+R", 0));
        actionSnapShot_2->setText(QApplication::translate("mainwindowClass", "snapshot", 0));
        actionSweepingAnimation->setText(QApplication::translate("mainwindowClass", "sweepingAnimation", 0));
        actionShow_skeletonConfidence->setText(QApplication::translate("mainwindowClass", "show skeletonConfidence", 0));
        actionShow_skeletonConfidence->setShortcut(QApplication::translate("mainwindowClass", "6", 0));
        actionShow_points->setText(QApplication::translate("mainwindowClass", "show points", 0));
        actionShow_points->setShortcut(QApplication::translate("mainwindowClass", "7", 0));
        actionShow_cullFace->setText(QApplication::translate("mainwindowClass", "cullFace", 0));
        actionShow_cullFace->setShortcut(QApplication::translate("mainwindowClass", "8", 0));
        actionShow_meshVertOnly->setText(QApplication::translate("mainwindowClass", "show meshVertOnly", 0));
        actionShow_meshVertOnly->setShortcut(QApplication::translate("mainwindowClass", "9", 0));
        actionShow_settings->setText(QApplication::translate("mainwindowClass", "show settings", 0));
        actionShow_settings->setShortcut(QApplication::translate("mainwindowClass", "0", 0));
        actionShow_trajectory_2->setText(QApplication::translate("mainwindowClass", "show trajectory", 0));
        actionShow_trajectory_2->setShortcut(QApplication::translate("mainwindowClass", "1", 0));
        actionShow_seedProfile->setText(QApplication::translate("mainwindowClass", "show seedProfile", 0));
        actionShow_seedProfile->setShortcut(QApplication::translate("mainwindowClass", "2", 0));
        actionShow_skeleton->setText(QApplication::translate("mainwindowClass", "show skeleton", 0));
        actionShow_skeleton->setShortcut(QApplication::translate("mainwindowClass", "3", 0));
        actionShow_mesh->setText(QApplication::translate("mainwindowClass", "show mesh", 0));
        actionShow_mesh->setShortcut(QApplication::translate("mainwindowClass", "4", 0));
        actionShow_resultProfile->setText(QApplication::translate("mainwindowClass", "show resultProfile", 0));
        actionShow_resultProfile->setShortcut(QApplication::translate("mainwindowClass", "5", 0));
        actionConfig->setText(QApplication::translate("mainwindowClass", "config", 0));
        actionShow_trajectory_3->setText(QApplication::translate("mainwindowClass", "show trajectory", 0));
        actionShow_seedProfile_2->setText(QApplication::translate("mainwindowClass", "show seedProfile", 0));
        actionShow_skeleton_2->setText(QApplication::translate("mainwindowClass", "show skeleton", 0));
        actionShow_mesh_2->setText(QApplication::translate("mainwindowClass", "show mesh", 0));
        actionShow_resultProfile_2->setText(QApplication::translate("mainwindowClass", "show resultProfile", 0));
        actionShow_skeletonConfidence_2->setText(QApplication::translate("mainwindowClass", "show skeletonConfidence", 0));
        actionShow_profileConfidence_2->setText(QApplication::translate("mainwindowClass", "show profileConfidence", 0));
        actionShow_cullFace_2->setText(QApplication::translate("mainwindowClass", "show cullFace", 0));
        actionShow_meshVertOnly_2->setText(QApplication::translate("mainwindowClass", "show meshVertOnly", 0));
        actionShow_settings_2->setText(QApplication::translate("mainwindowClass", "show settings", 0));
        actionShow_cutRadii_2->setText(QApplication::translate("mainwindowClass", "show cutRadii", 0));
        menuFile->setTitle(QApplication::translate("mainwindowClass", "File", 0));
        menuRender->setTitle(QApplication::translate("mainwindowClass", "render", 0));
        menuOperations->setTitle(QApplication::translate("mainwindowClass", "operations", 0));
    } // retranslateUi

};

namespace Ui {
    class mainwindowClass: public Ui_mainwindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
